import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { IPadMockup } from 'react-device-mockup';
import Tilt from 'react-parallax-tilt';
import { useMediaQuery } from '../hooks/useMediaQuery.js';
import manifest from '../assets/food-thumbs/manifest.json';
import './FoodAlbum.css';

// generated by scripts/generate-food-thumbnails.mjs (sharp) — every entry is
// already a uniform, center-cropped square, so the grid never has to stretch
// or letterbox anything itself. This is the LOCAL fallback: it's what renders
// in plain `vite` dev (no serverless functions), and whenever the deployed
// /api/food-images call below fails or comes back empty.
const thumbsByFile = Object.fromEntries(
  Object.entries(
    import.meta.glob('../assets/food-thumbs/*.webp', {
      eager: true,
      query: '?url',
      import: 'default',
    })
  ).map(([path, url]) => [path.split('/').pop(), url])
);

// the original, uncropped photos — used only for the full-screen detail view
// (browsers auto-rotate JPEGs per EXIF, so these need no extra processing)
const originalsByFile = Object.fromEntries(
  Object.entries(
    import.meta.glob(
      '../assets/food/*.{jpg,jpeg,jfif,png,avif,webp,gif,heic,heif,JPG,JPEG,PNG,AVIF,WEBP,HEIC}',
      { eager: true, query: '?url', import: 'default' }
    )
  ).map(([path, url]) => [path.split('/').pop(), url])
);

function sortByTakenAt(list) {
  return [...list].sort((a, b) => (Date.parse(b.takenAt) || 0) - (Date.parse(a.takenAt) || 0));
}

// newest first, row-major, top-left -> bottom-right
const localPhotos = sortByTakenAt(manifest)
  .map((p) => ({
    id: p.id,
    url: thumbsByFile[p.file],
    fullUrl: originalsByFile[p.srcFile] || thumbsByFile[p.file],
    place: p.place,
    caption: p.caption,
    takenAt: p.takenAt,
  }))
  .filter((p) => p.url);

function formatDetailDate(iso) {
  if (!iso) return null;
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return null;
  const day = date.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const time = date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
  return `${day}  ${time}`;
}

function WifiIcon() {
  return (
    <svg viewBox="0 0 16 12" fill="currentColor" aria-hidden="true">
      <path d="M8 11.2 6.1 9.1a2.6 2.6 0 0 1 3.8 0L8 11.2zM4.6 7.5A5 5 0 0 1 8 6.2c1.3 0 2.5.5 3.4 1.3l1.2-1.3A6.8 6.8 0 0 0 8 4.4c-1.8 0-3.4.7-4.6 1.8l1.2 1.3zM1.9 4.6A8.9 8.9 0 0 1 8 2.3c2.4 0 4.5.9 6.1 2.3l1.2-1.3A10.6 10.6 0 0 0 8 .6C5 .6 2.3 1.7.7 3.3l1.2 1.3z" />
    </svg>
  );
}

function BatteryIcon() {
  return (
    <svg viewBox="0 0 26 12" fill="none" aria-hidden="true">
      <rect x="0.6" y="0.6" width="21" height="10.8" rx="3" stroke="currentColor" strokeOpacity="0.4" strokeWidth="1.1" />
      <rect x="2.1" y="2.1" width="18" height="7.8" rx="1.8" fill="currentColor" />
      <path d="M23.4 4.3v3.4a2 2 0 0 0 0-3.4z" fill="currentColor" fillOpacity="0.4" />
    </svg>
  );
}

// static — mirrors the macOS/iPadOS Photos sidebar, not wired to anything
const SIDEBAR_ITEMS = [
  { label: 'All Photos', icon: '▣', active: true },
  { label: 'Favorites', icon: '♡' },
  { label: 'Edited Photos', icon: '✎' },
  { label: 'Live Photos', icon: '◎' },
  { label: 'Portrait Photos', icon: '◉' },
  { label: 'Selfies', icon: '☺' },
  { label: 'Imported', icon: '⇩' },
  { label: 'Screenshots', icon: '▢' },
  { label: 'Panoramas', icon: '▭' },
  { label: 'Hidden Photos', icon: '⊘' },
];

// decorative only — mirrors the iOS Photos detail view's action row
const DETAIL_ACTIONS = ['⤴', '♡', 'ⓘ', '◐', '🗑'];

// ---------- sizing ----------
// react-device-mockup (IPadModernLandscape, frameOnly) derives every
// dimension from screenWidth with these ratios; mirrored here so the device
// can be fitted to the space the panel actually has.
const bezelOf = (sw) => Math.max(Math.floor((sw * 35) / 1194), 1);
const radiusOf = (sw) => Math.max(Math.floor((sw * 50) / 1194), 1);
const screenHeightOf = (sw) => Math.floor((sw * 3) / 4);

const SW_MIN = 240;
const SW_MAX = 1600;
const FRAME_PAD = 10; // .food-album-frame padding
const TILT_HEADROOM = 0.96; // a tilted edge swings toward the viewer and grows

// the app UI is authored at this logical width; bigger screens zoom it up,
// small ones zoom it down, and anything in between renders 1:1
const DESIGN_MIN = 560;
const DESIGN_MAX = 720;

function fitScreenWidth(boxW, boxH) {
  const w = (boxW - 2 * FRAME_PAD) * TILT_HEADROOM;
  const h = (boxH - 2 * FRAME_PAD) * TILT_HEADROOM;
  const bezelRatio = 70 / 1194;
  let sw = Math.floor(Math.min(w / (1 + bezelRatio), h / (0.75 + bezelRatio), SW_MAX));
  // the library floors each dimension, so nudge down until it truly fits
  while (sw > SW_MIN && (sw + 2 * bezelOf(sw) > w || screenHeightOf(sw) + 2 * bezelOf(sw) > h)) {
    sw -= 1;
  }
  return Math.max(sw, SW_MIN);
}

// When the panel is a fixed 100vh (scroll-driven Showcase) the iPad fills the
// stage's measured width AND height. Otherwise the panel's height comes from
// its content, so only width is measured and height is capped to the viewport.
function useFittedScreenWidth(fitHeight) {
  const stageRef = useRef(null);
  const [screenWidth, setScreenWidth] = useState(720);

  useLayoutEffect(() => {
    const el = stageRef.current;
    if (!el) return undefined;

    // clientWidth/clientHeight are layout sizes, unaffected by the scale
    // transform Showcase applies to panels while scrolling
    const measure = () => {
      const maxH = fitHeight ? el.clientHeight : window.innerHeight * 0.72;
      const next = fitScreenWidth(el.clientWidth, maxH);
      setScreenWidth((prev) => (prev === next ? prev : next));
    };

    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    window.addEventListener('resize', measure);
    return () => {
      observer.disconnect();
      window.removeEventListener('resize', measure);
    };
  }, [fitHeight]);

  return [stageRef, screenWidth];
}

// ---------- tilt ----------
// offset is 0 at the device's centre and 1 at its edge
const TILT_KNEE = 0.9; // offset where the tilt reaches TILT_AT_KNEE
const TILT_AT_KNEE = 1.6; // degrees
const TILT_MAX = 2.5; // degrees, right at the edge
const TILT_CURVE = 3; // below the knee: keeps the centre effectively flat
const TILT_SPEED = 450;
const TILT_STYLE = { transition: `all ${TILT_SPEED}ms cubic-bezier(.03,.98,.52,.99)` };

function tiltDegrees(n) {
  const offset = Math.min(1, Math.abs(n));
  const degrees =
    offset <= TILT_KNEE
      ? TILT_AT_KNEE * (offset / TILT_KNEE) ** TILT_CURVE
      : TILT_AT_KNEE + (TILT_MAX - TILT_AT_KNEE) * ((offset - TILT_KNEE) / (1 - TILT_KNEE));
  return Math.sign(n) * degrees;
}

// react-parallax-tilt maps pointer offset to angle linearly. We track the
// pointer ourselves and hand it shaped manual angles instead, so the middle of
// the screen stays flat and the tilt only builds right at the edges.
function DeviceTilt({ enabled, radius, perspective, children }) {
  const [angles, setAngles] = useState({ x: 0, y: 0 });
  const latest = useRef(angles);
  const frame = useRef(0);

  useEffect(() => () => cancelAnimationFrame(frame.current), []);

  const schedule = (next) => {
    latest.current = next;
    if (frame.current) return;
    frame.current = requestAnimationFrame(() => {
      frame.current = 0;
      setAngles(latest.current);
    });
  };

  const onPointerMove = (e) => {
    if (!enabled || e.pointerType !== 'mouse') return;
    const rect = e.currentTarget.getBoundingClientRect();
    const nx = ((e.clientX - rect.left) / rect.width) * 2 - 1;
    const ny = ((e.clientY - rect.top) / rect.height) * 2 - 1;
    // same direction convention as the library's own pointer mode, just eased
    schedule({ x: tiltDegrees(ny), y: -tiltDegrees(nx) });
  };

  const onPointerLeave = () => schedule({ x: 0, y: 0 });

  return (
    <div className="food-album-frame" onPointerMove={onPointerMove} onPointerLeave={onPointerLeave}>
      <Tilt
        className="food-album-tilt"
        style={{ ...TILT_STYLE, borderRadius: radius }}
        tiltEnable={enabled}
        tiltAngleXManual={angles.x}
        tiltAngleYManual={angles.y}
        tiltMaxAngleX={TILT_MAX}
        tiltMaxAngleY={TILT_MAX}
        perspective={perspective}
        transitionSpeed={TILT_SPEED}
        glareEnable={enabled}
        glareMaxOpacity={0.12}
        glarePosition="all"
        glareBorderRadius={`${radius}px`}
      >
        {children}
      </Tilt>
    </div>
  );
}

export default function FoodAlbum({ fitHeight = false }) {
  const [photos, setPhotos] = useState(localPhotos);
  const [openId, setOpenId] = useState(null);
  const [stageRef, screenWidth] = useFittedScreenWidth(fitHeight);

  const canHover = useMediaQuery('(hover: hover) and (pointer: fine)');
  const reduceMotion = useMediaQuery('(prefers-reduced-motion: reduce)');
  const tiltEnabled = canHover && !reduceMotion;

  // deployed (Vercel) serves this from api/food-images.js, which lists the
  // shared Google Drive folder directly — real place/caption/date metadata,
  // no rebuild needed to add a photo. `vite` dev has no serverless functions
  // running, so the request 404s and we just keep the local sharp fallback.
  useEffect(() => {
    let cancelled = false;
    fetch('/api/food-images')
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (!cancelled && data?.images?.length) {
          setPhotos(
            sortByTakenAt(
              data.images.map((img) => ({
                id: img.id,
                url: img.url,
                fullUrl: img.url,
                place: img.place || null,
                caption: img.caption || null,
                takenAt: img.takenAt || null,
              }))
            )
          );
        }
      })
      .catch(() => {}); // keep the local fallback
    return () => {
      cancelled = true;
    };
  }, []);

  const zoom = screenWidth / Math.min(DESIGN_MAX, Math.max(DESIGN_MIN, screenWidth));
  const screenHeight = screenHeightOf(screenWidth);

  const openIndex = photos.findIndex((p) => p.id === openId);
  const openPhoto = openIndex >= 0 ? photos[openIndex] : null;
  const closeDetail = () => setOpenId(null);
  const showPrev = () => setOpenId(photos[(openIndex - 1 + photos.length) % photos.length]?.id);
  const showNext = () => setOpenId(photos[(openIndex + 1) % photos.length]?.id);

  return (
    <>
      <div className="panel-head">
        <span className="section-label">Off the clock</span>
        <h2 className="panel-title display">Every plate, one album.</h2>
      </div>

      <div ref={stageRef} className={`food-album-stage${fitHeight ? ' is-fit' : ''}`}>
        <DeviceTilt
          enabled={tiltEnabled}
          radius={radiusOf(screenWidth)}
          perspective={Math.round(screenWidth * 2.2)}
        >
          <IPadMockup
            screenWidth={screenWidth}
            isLandscape
            hideStatusBar
            hideNavBar
            frameOnly
            frameColor="#1c1c1e"
          >
            <div
              className="fa-screen"
              style={{ width: screenWidth / zoom, height: screenHeight / zoom, zoom }}
            >
              <div className="fa-statusbar">
                <span className="fa-statusbar-left">
                  <b>9:41&nbsp;AM</b>
                  <span>Mon Jun 22</span>
                </span>
                <span className="fa-statusbar-right">
                  <WifiIcon />
                  <span>100%</span>
                  <BatteryIcon />
                </span>
              </div>

              <div className="fa-app">
                <aside className="fa-sidebar">
                  <div className="fa-sidebar-head">
                    <span aria-hidden="true">&#9881;</span>
                  </div>

                  <nav className="fa-sidebar-nav">
                    {SIDEBAR_ITEMS.map((item) => (
                      <div
                        key={item.label}
                        className={`fa-sidebar-row${item.active ? ' active' : ''}`}
                      >
                        <span className="fa-icon" aria-hidden="true">
                          {item.icon}
                        </span>
                        <span>{item.label}</span>
                      </div>
                    ))}
                  </nav>

                  <div className="fa-sidebar-albums-head">Albums</div>
                  {photos.length > 0 && (
                    <div className="fa-album-entry active">
                      <div className="fa-album-thumb">
                        <img src={photos[0].url} alt="" />
                      </div>
                      <div className="fa-album-meta">
                        <span className="fa-album-name">Food</span>
                        <span className="fa-album-count">{photos.length} photos</span>
                      </div>
                    </div>
                  )}
                </aside>

                <div className="fa-main">
                  <header className="fa-topbar">
                    <span className="fa-topbar-title">Food</span>
                    <span className="fa-topbar-action">Batch</span>
                  </header>

                  {photos.length ? (
                    <div className="fa-grid">
                      {photos.map((p) => (
                        <button
                          type="button"
                          className="fa-thumb"
                          key={p.id}
                          title={[p.place, p.caption].filter(Boolean).join(' — ')}
                          onClick={() => setOpenId(p.id)}
                        >
                          <img src={p.url} alt={p.caption || p.place || ''} loading="lazy" />
                        </button>
                      ))}
                    </div>
                  ) : (
                    <p className="fa-empty mono">Drop photos in src/assets/food/</p>
                  )}
                </div>

                {openPhoto && (
                  <div className="fa-detail">
                    <header className="fa-detail-bar">
                      <button
                        type="button"
                        className="fa-detail-back"
                        onClick={closeDetail}
                        aria-label="Back to album"
                      >
                        &#8249;
                      </button>
                      <div className="fa-detail-title">
                        <span className="fa-detail-place">{openPhoto.place || 'Food'}</span>
                        {formatDetailDate(openPhoto.takenAt) && (
                          <span className="fa-detail-date">
                            {formatDetailDate(openPhoto.takenAt)}
                          </span>
                        )}
                      </div>
                      <span className="fa-detail-more" aria-hidden="true">
                        &#8226;&#8226;&#8226;
                      </span>
                    </header>

                    <div className="fa-detail-stage">
                      {photos.length > 1 && (
                        <button
                          type="button"
                          className="fa-detail-nav fa-detail-nav--prev"
                          onClick={showPrev}
                          aria-label="Previous photo"
                        >
                          &#8249;
                        </button>
                      )}
                      <img
                        key={openPhoto.id}
                        className="fa-detail-photo"
                        src={openPhoto.fullUrl}
                        alt={openPhoto.caption || openPhoto.place || ''}
                      />
                      {photos.length > 1 && (
                        <button
                          type="button"
                          className="fa-detail-nav fa-detail-nav--next"
                          onClick={showNext}
                          aria-label="Next photo"
                        >
                          &#8250;
                        </button>
                      )}
                    </div>

                    {openPhoto.caption && (
                      <p className="fa-detail-caption">{openPhoto.caption}</p>
                    )}

                    {photos.length > 1 && (
                      <div className="fa-detail-filmstrip">
                        {photos.map((p) => (
                          <button
                            type="button"
                            key={p.id}
                            className={`fa-detail-filmthumb${p.id === openId ? ' active' : ''}`}
                            onClick={() => setOpenId(p.id)}
                            aria-label={p.caption || p.place || 'Photo'}
                          >
                            <img src={p.url} alt="" />
                          </button>
                        ))}
                      </div>
                    )}

                    <div className="fa-detail-actions" aria-hidden="true">
                      {DETAIL_ACTIONS.map((icon, i) => (
                        <span key={i}>{icon}</span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
              <div className="fa-home" aria-hidden="true" />
            </div>
          </IPadMockup>
        </DeviceTilt>
      </div>
    </>
  );
}
